### PR TITLE
Relax RSpec dependency

### PR DESCRIPTION
**Pull request by pacoguzman**
There is a new major version of RSpec 4 that cannot be used due to this dependency restriction.

### CODE REVIEW

**Comment by pacoguzman** [comment]
This is a work in progress, I'm thinking that maybe is worth it to migrate from Travis to GitHub Actions so we can test even more combinations mixing RSpec versions too. What do you think?

**Comment by kbrock** [comment]
> Actions so we can test even more combinations mixing RSpec versions too

seems like a little bit of overkill.
But you know your use case / risk aversion better than I.

For this use case, I tend to use the appraisal gem for this use case

e.g.: https://github.com/stefankroes/ancestry/blob/master/Appraisals

**Comment by iarie** [comment]
Hello, guys! Any updates with that?
Eager to see these changes go live

**Comment by kbrock** [comment]
as followup: I'm going over to github actions myself as travis and OSS has not been working too well for me.

Best of luck

**Pull request merged**
