### PR TITLE
Allow Rails 7.1.x

### LINKED ISSUE #55: Support Rails 7.1
Hi, Rails 7.1.0 is out, is it possible to allow/support in this gem? Thanks!

### PR DESCRIPTION
**Pull request by jrochkind**
Looks like all tests pass as-is, just needed to allow Rails 7.1 in gemspec. 

Closes #55

### CODE REVIEW

**Comment by jrochkind** [comment]
uh oh, are you still running builds on travis? That isn't going to work I think, travis doesn't really give free resources to open source anymore. 

I don't understand the conflict, trying to work it out.

**Comment by jrochkind** [comment]
I have run tests manually locally on Rails 7.1.0

```
jrochkind-shi db-query-matchers (allow_rails_7.1) $ bundle show activesupport
/Users/jrochkind/.gem/ruby/3.2.2/gems/activesupport-7.1.0

jrochkind-shi db-query-matchers (allow_rails_7.1) $ bundle show activerecord
/Users/jrochkind/.gem/ruby/3.2.2/gems/activerecord-7.1.0

jrochkind-shi db-query-matchers (allow_rails_7.1) $ bundle exec rspec
...................................................................

Finished in 0.04188 seconds (files took 0.60796 seconds to load)
67 examples, 0 failures


jrochkind-shi db-query-matchers (allow_rails_7.1) $
```

**Comment by jrochkind** [comment]
Oh hey, Github Actions CI is running, ok, I'll try to add a Rails 7.1 to build!

**Comment by jrochkind** [comment]
Appraisals were testing with sqlite3 `"~> 1.4"`, which is 1.4.x only, when sqlite3 1.6 is out. I don't think you meant to lock to 1.4.x; will open it up at least for latest Rails.

**Comment by jrochkind** [comment]
OK, I notice this is still only testing with ruby 3.0. 

I can add in ruby 3.1 and 3.2.  I think it makes sense to switch the CI matrix to be include-only. I can do all that in a separate PR once this is approved/merged.

**Comment by owst** [comment]
@sds as a previous committer to this repo - could you take a look at this PR and merge/release if happy? Thanks!

**Comment by hlascelles** [comment]
@trotzig If you still have commit rights...?

**Comment by ckhall** [comment]
bump

**Comment by jrochkind** [comment]
@sds or anyone else, is this gem still maintained? Any chance of a merge and release?  Should we consider forking to get a release that works with Rails 7.1?

**Comment by hlascelles** [comment]
@sds do say if you have anything that you'd like to change about this before a merge! :bow:

**Comment by scottwhudson** [comment]
@sds @rafaelsales Do you have any guidance on the future of this project? This issue is currently blocking our upgrade to Rails 7.1

**Pull request merged**
