### PR TITLE
Allow Rails 7.0

### PR DESCRIPTION
**Pull request by tagliala**
Also:
- Moves to GitHub Actions
- Updates badges
- Test against Ruby head and Rails edge

You can take a look at the results of the CI here: https://github.com/tagliala/db-query-matchers/pull/1/checks

Someone with permissions should enable workflows on this PR

### CODE REVIEW

**Review by varyonic — APPROVED** [review]

**Comment by varyonic** [comment]
@sds ?

**Comment by djezzzl** [comment]
Hello :wave: 

Is there any reasons why it isn't merged yet? I'd like to use the gem for Rails 7 project but the dependency boundaries are falling for me. 

Maybe we should split the PR to two separate thing: one for Github Actions migrations another for Rails 7 support (if that's the reason of not merging this). 

BTW, do we really need upper boundary on `activerecord < 7.1`?

**Review by geoffharcourt — APPROVED** [review]

**Comment by jrochkind** [comment]
Hi, any update? @sds @varyonic @geoffharcourt , is anything blocking a merge and release? 

I have some things I need to test under 7.0.  I was considering whether to try to replace this gem with something else wondering if it was maintained, but it looks like it is maintained, there's lots of committer activity here, great! And thank you for your work!  

Re @djezzzl , 

> BTW, do we really need upper boundary on activerecord < 7.1?

I personally think that is appropriate, yeah.  There is no guarantee something reaching into the inners of Rails like this will work with subsequent rails releases, it's appropriate to put the boundary on currently tested versions, not assume it will work with future versions. But that only works if releases are done! :)

**Comment by jrochkind** [comment]
(I'd also encourage a 1.0 release with this!)

**Comment by bfad** [comment]
With two approvals form maintainers, what's preventing this from being merged and released?

**Comment by kbrock** [comment]
Hey all, this looks great. Anything we can do to help release the next version of this gem?

**Pull request merged**
